import { Routes, Route } from "react-router-dom";
import { useState, useEffect, useCallback, Component, type ReactNode } from "react";
import { initAuth, loadProfile, isAutoGeneratedNickname, type AuthState } from "./lib/auth";
import { isTossApp } from "./lib/toss";
import type { Profile } from "./types";
import Layout from "./components/Layout";
import Home from "./pages/Home";
import SoloQuest from "./pages/SoloQuest";
import PartyCreate from "./pages/PartyCreate";
import PartyDetail from "./pages/PartyDetail";
import PartyPlay from "./pages/PartyPlay";
import NicknameSetup from "./pages/NicknameSetup";

class ErrorBoundary extends Component<{ children: ReactNode }, { hasError: boolean }> {
  state = { hasError: false };
  static getDerivedStateFromError() { return { hasError: true }; }
  componentDidCatch(error: Error) { console.error("[ErrorBoundary]", error); }
  render() {
    if (this.state.hasError) {
      return (
        <div className="flex flex-col items-center justify-center h-screen p-6 bg-(--tds-bg) text-center">
          <div className="text-5xl mb-4">😿</div>
          <h2 className="text-lg font-bold text-(--tds-text) mb-2">문제가 발생했다냥...</h2>
          <p className="text-sm text-(--tds-text-secondary) mb-6">다시 시도해보라냥</p>
          <button
            onClick={() => { this.setState({ hasError: false }); window.location.reload(); }}
            className="px-6 py-3 bg-(--tds-blue) text-(--tds-text) rounded-xl font-medium active:scale-95 transition-transform"
          >
            새로고침
          </button>
        </div>
      );
    }
    return this.props.children;
  }
}

type AppState = "loading" | "unauthenticated" | "nickname-setup" | "ready";

export default function App() {
  const [appState, setAppState] = useState<AppState>("loading");
  const [profile, setProfile] = useState<Profile | null>(null);
  const [authError, setAuthError] = useState("");

  const doAuth = useCallback(async () => {
    setAppState("loading");
    setAuthError("");
    try {
      const ok = await initAuth();
      if (!ok) {
        setAuthError(isTossApp() ? "토스 로그인에 실패했다냥" : "토스 앱에서만 사용할 수 있다냥");
        setAppState("unauthenticated");
        return;
      }
      const p = await loadProfile();
      setProfile(p);
      if (p && isAutoGeneratedNickname(p.nickname)) {
        setAppState("nickname-setup");
      } else {
        setAppState("ready");
      }
    } catch (e) {
      console.error("[App] Auth init failed:", e);
      setAuthError(String(e));
      setAppState("unauthenticated");
    }
  }, []);

  useEffect(() => {
    doAuth();
  }, [doAuth]);

  if (appState === "loading") {
    return (
      <div className="flex items-center justify-center h-screen bg-(--tds-bg)">
        <div className="text-center">
          <div className="text-5xl animate-bounce">🐱</div>
          <p className="text-(--tds-text-secondary) mt-3 text-sm">냥퀘스트 로딩 중...</p>
        </div>
      </div>
    );
  }

  if (appState === "unauthenticated") {
    return (
      <div className="flex flex-col items-center justify-center h-screen p-6 bg-(--tds-bg) text-center">
        <div className="text-5xl mb-4">🔒</div>
        <h2 className="text-lg font-bold text-(--tds-text) mb-2">로그인이 필요하다냥!</h2>
        <p className="text-sm text-(--tds-text-secondary) mb-6">
          냥퀘스트를 즐기려면 토스 로그인이 필요해요
        </p>
        <button
          onClick={doAuth}
          className="px-6 py-3 bg-(--tds-blue) text-(--tds-text) rounded-xl font-medium active:scale-95 transition-transform"
        >
          토스 로그인 다시 시도
        </button>
        {authError && (
          <p className="text-[10px] text-(--tds-text-disabled) mt-6 max-w-xs break-all">
            {authError}
          </p>
        )}
      </div>
    );
  }

  if (appState === "nickname-setup" && profile) {
    return (
      <NicknameSetup
        profile={profile}
        onComplete={(updated) => {
          setProfile(updated);
          setAppState("ready");
        }}
      />
    );
  }

  return (
    <ErrorBoundary>
      <Layout profile={profile}>
        <Routes>
          <Route path="/" element={<Home profile={profile} />} />
          <Route path="/solo/:scenarioId" element={<SoloQuest profile={profile} />} />
          <Route path="/party/create" element={<PartyCreate profile={profile} />} />
          <Route path="/party/:partyId" element={<PartyDetail profile={profile} />} />
          <Route path="/party/:partyId/play" element={<PartyPlay profile={profile} />} />
        </Routes>
      </Layout>
    </ErrorBoundary>
  );
}
